package prueba;

import Interfaz.InterfazCPU;
import Interfaz.InterfazGPU;
import Interfaz.InterfazInfo;
import Interfaz.InterfazInternet1;
import Interfaz.InterfazRAM;
import Interfaz.InterfazStorage;
import Interfaz.InterfazSystem;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hyperic.sigar.SigarException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author franco
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CPU_btn = new javax.swing.JButton();
        RAM_btn = new javax.swing.JButton();
        GPU_btn = new javax.swing.JButton();
        Storage_btn = new javax.swing.JButton();
        Internet_btn = new javax.swing.JButton();
        System_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EXIT_btn = new javax.swing.JButton();
        Info_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CPU_btn.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        CPU_btn.setText("CPU");
        CPU_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPU_btnActionPerformed(evt);
            }
        });

        RAM_btn.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        RAM_btn.setText("RAM");
        RAM_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAM_btnActionPerformed(evt);
            }
        });

        GPU_btn.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        GPU_btn.setText("GPU");
        GPU_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPU_btnActionPerformed(evt);
            }
        });

        Storage_btn.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        Storage_btn.setText("Storage");
        Storage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Storage_btnActionPerformed(evt);
            }
        });

        Internet_btn.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        Internet_btn.setText("Internet");
        Internet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Internet_btnActionPerformed(evt);
            }
        });

        System_btn.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        System_btn.setText("System");
        System_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        jLabel1.setText("Proyecto Info CPU");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        jLabel2.setText("Ebner Lautaro y Molina Franco");

        EXIT_btn.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        EXIT_btn.setText("Exit");
        EXIT_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT_btnActionPerformed(evt);
            }
        });

        Info_btn.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        Info_btn.setText("Info");
        Info_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_btnActionPerformed(evt);
            }
        });

        jLabel3.setText("Project to detect ");

        jLabel4.setText("the internal characteristics");

        jLabel5.setText("of the computer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(GPU_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Internet_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Storage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CPU_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RAM_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(System_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Info_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(EXIT_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Storage_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addComponent(CPU_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(RAM_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(System_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPU_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Internet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Info_btn)
                        .addComponent(EXIT_btn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXIT_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EXIT_btnActionPerformed

    private void Info_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_btnActionPerformed
        // TODO add your handling code here:
        InterfazInfo info = new InterfazInfo();
        this.setVisible(false);
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Info_btnActionPerformed

    private void Internet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Internet_btnActionPerformed
        // TODO add your handling code here:
        InterfazInternet1 internet = new InterfazInternet1();
        this.setVisible(false);
        internet.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Internet_btnActionPerformed

    private void GPU_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPU_btnActionPerformed
        // TODO add your handling code here:
        InterfazGPU gpu = new InterfazGPU();
        this.setVisible(false);
        gpu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GPU_btnActionPerformed

    private void System_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_System_btnActionPerformed
        // TODO add your handling code here:
        InterfazSystem system = new InterfazSystem();
        this.setVisible(false);
        system.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_System_btnActionPerformed

    private void RAM_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAM_btnActionPerformed
        // TODO add your handling code here:
        InterfazRAM ram = null;
        try {
            ram = new InterfazRAM();
        } catch (SigarException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        ram.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RAM_btnActionPerformed

    private void CPU_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPU_btnActionPerformed
        // TODO add your handling code here:
        InterfazCPU cpu = null;
        try {
            cpu = new InterfazCPU();
        } catch (SigarException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        cpu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CPU_btnActionPerformed

    private void Storage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Storage_btnActionPerformed
        // TODO add your handling code here:
        InterfazStorage storage = new InterfazStorage();
        this.setVisible(false);
        storage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Storage_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CPU_btn;
    private javax.swing.JButton EXIT_btn;
    private javax.swing.JButton GPU_btn;
    private javax.swing.JButton Info_btn;
    private javax.swing.JButton Internet_btn;
    private javax.swing.JButton RAM_btn;
    private javax.swing.JButton Storage_btn;
    private javax.swing.JButton System_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
