/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import clases.Sistema_clase;
import prueba.MainFrame;

/**
 *
 * @author franco
 */
public class InterfazSystem extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCpu
     */
    public InterfazSystem() {
        initComponents();
        new Sistema_clase();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        so_lbl = new javax.swing.JLabel();
        aso_lbl = new javax.swing.JLabel();
        vso_lbl = new javax.swing.JLabel();
        home_lbl = new javax.swing.JLabel();
        Volver_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        uptime_lbl = new javax.swing.JLabel();
        usu_lbl = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 24)); // NOI18N
        jLabel1.setText("System Info");

        so_lbl.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        so_lbl.setText("............................");

        aso_lbl.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        aso_lbl.setText("............................");

        vso_lbl.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        vso_lbl.setText("............................");

        home_lbl.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        home_lbl.setText("............................");

        Volver_btn.setFont(new java.awt.Font("Noto Sans", 3, 36)); // NOI18N
        Volver_btn.setText("←");
        Volver_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel6.setText("Sistema Operativo:");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel7.setText("Arquitectura del SO:");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel8.setText("Version del SO:");

        jLabel9.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel9.setText("Ruta del Home:");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel10.setText("Nombre del usuario:");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel11.setText("Uptime:");

        uptime_lbl.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        uptime_lbl.setText("............................");

        usu_lbl.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        usu_lbl.setText("............................");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volver_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aso_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vso_lbl)
                                    .addComponent(so_lbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uptime_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usu_lbl, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Volver_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(so_lbl)
                            .addComponent(jLabel10)
                            .addComponent(usu_lbl)
                            .addComponent(jLabel6))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(uptime_lbl)
                            .addComponent(aso_lbl)
                            .addComponent(jLabel7))))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vso_lbl)
                    .addComponent(jLabel9)
                    .addComponent(home_lbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btnActionPerformed
        // TODO add your handling code here:
        MainFrame main = new MainFrame();
        this.setVisible(false);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volver_btnActionPerformed

    private void refresh(){
        so_lbl.setText(Sistema_clase.getSist_op());
        aso_lbl.setText(Sistema_clase.getArqui_so());
        vso_lbl.setText(Sistema_clase.getVersio_os());
        uptime_lbl.setText(Sistema_clase.getUptime_1());
        home_lbl.setText(Sistema_clase.getRuta_home());
        usu_lbl.setText(Sistema_clase.getNombre_usu());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver_btn;
    private javax.swing.JLabel aso_lbl;
    private javax.swing.JLabel home_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel so_lbl;
    private javax.swing.JLabel uptime_lbl;
    private javax.swing.JLabel usu_lbl;
    private javax.swing.JLabel vso_lbl;
    // End of variables declaration//GEN-END:variables
}
